# Generated by Django 2.2 on 2020-11-04 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20201104_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='moderator',
            field=models.BooleanField(default=False),
        ),
    ]
