# Generated by Django 2.2 on 2020-11-04 01:41

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.URLField(max_length=500),
        ),
    ]
